# Generated by Django 4.2 on 2023-09-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('marks', models.IntegerField()),
            ],
            options={
                'db_table': 'B8_REST_Student',
            },
        ),
    ]
